2023-03-03T00:28:58.206319+00:00 app[worker.1]:     api_kwargs=api_kwargs,
2023-03-03T00:28:58.206319+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 296, in _message
2023-03-03T00:28:58.206319+00:00 app[worker.1]:     result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
2023-03-03T00:28:58.206320+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 260, in _post
2023-03-03T00:28:58.206320+00:00 app[worker.1]:     f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
2023-03-03T00:28:58.206320+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 355, in post
2023-03-03T00:28:58.206320+00:00 app[worker.1]:     **urlopen_kwargs,
2023-03-03T00:28:58.206320+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 273, in _request_wrapper
2023-03-03T00:28:58.206320+00:00 app[worker.1]:     raise BadRequest(message)
2023-03-03T00:28:58.206328+00:00 app[worker.1]: telegram.error.BadRequest: Can't parse entities: can't find end of the entity starting at byte offset 62


 2023-03-03 00:43:54,719 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
2023-03-03T00:43:54.723927+00:00 app[worker.1]: Traceback (most recent call last):
2023-03-03T00:43:54.723928+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 447, in process_update
2023-03-03T00:43:54.723929+00:00 app[worker.1]:     handler.handle_update(update, self, check, context)
2023-03-03T00:43:54.723929+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 602, in handle_update
2023-03-03T00:43:54.723930+00:00 app[worker.1]:     new_state = handler.handle_update(update, dispatcher, check_result, context)
2023-03-03T00:43:54.723930+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 160, in handle_update
2023-03-03T00:43:54.723931+00:00 app[worker.1]:     return self.callback(update, context)
2023-03-03T00:43:54.723931+00:00 app[worker.1]:   File "/app/bot.py", line 288, in follow_twitter
2023-03-03T00:43:54.723931+00:00 app[worker.1]:     update.message.reply_text(text=FOLLOW_TWITTER_TEXT, parse_mode=telegram.ParseMode.MARKDOWN)
2023-03-03T00:43:54.723932+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/message.py", line 715, in reply_text
2023-03-03T00:43:54.723933+00:00 app[worker.1]:     entities=entities,
2023-03-03T00:43:54.723933+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 127, in decorator
2023-03-03T00:43:54.723933+00:00 app[worker.1]:     result = func(*args, **kwargs)
2023-03-03T00:43:54.723934+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 483, in send_message
2023-03-03T00:43:54.723935+00:00 app[worker.1]:     api_kwargs=api_kwargs,
2023-03-03T00:43:54.723935+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 296, in _message
2023-03-03T00:43:54.723936+00:00 app[worker.1]:     result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
2023-03-03T00:43:54.723936+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/bot.py", line 260, in _post
2023-03-03T00:43:54.723937+00:00 app[worker.1]:     f'{self.base_url}/{endpoint}', data=data, timeout=effective_timeout
2023-03-03T00:43:54.723937+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 355, in post
2023-03-03T00:43:54.723937+00:00 app[worker.1]:     **urlopen_kwargs,
2023-03-03T00:43:54.723937+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/site-packages/telegram/utils/request.py", line 273, in _request_wrapper
2023-03-03T00:43:54.723938+00:00 app[worker.1]:     raise BadRequest(message)
2023-03-03T00:43:54.723938+00:00 app[worker.1]: telegram.error.BadRequest: Can't parse entities: can't find end of the entity starting at byte offset 62
